source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'bootstrap', '~> 4.0.0'
gem 'coffee-rails', '~> 4.2' # Use CoffeeScript for .coffee assets and views
gem 'devise' # Used for login authentication
gem 'dotenv-rails' # Used for environment configuration
gem 'font-awesome-rails' # Replace Bootstrap 4's missing glyphicons
gem 'haml-rails' # Use HAML for .haml views
gem 'jbuilder', '~> 2.5' # Build JSON APIs with ease
gem 'jquery-rails'
gem 'mysql2' # Use MySQL2 for the database
gem 'paperclip' #for storing files in the database
gem 'puma', '~> 3.7'
gem 'rails', '~> 5.1.4'
gem 'remotipart', github: 'spdawson/remotipart'
gem 'sass-rails', '~> 5.0' # Use SCSS for .scss stylesheets
gem 'uglifier' # For asset compilation
gem 'turbolinks', '~> 5'

group :development, :test do
  gem 'faker' # Allow us to create fake data for tests
  gem 'pry-byebug' # Use pry and byebug commands for debugging
  gem 'rspec-rails' # Use the rspec test framework
end

group :development do
  gem 'letter_opener' # Allows us to preview emails rather than send them
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring' # Spring speeds up development by keeping your application running in the background
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0' # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
end

group :test do
  gem 'capybara-webkit' # Use the capybara-webkit JS test framework
  gem 'database_cleaner' # Use database_cleaner to manage test database cleanup
  gem 'factory_bot_rails' # Use factory_bot to easily build spec model factories
  gem 'rails-controller-testing' # Use gem for controller tests
  gem 'shoulda-matchers' # Provides extended matchers for spec coverage
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
