chart_colors:
  light_blue: '#0E78C5'
  light_blue_50: '#6FB9E2'
  light_green: '#67B419'
  light_green_50: '#AEDB7D'
  torquoise: '#1399A0'
  torquoise_50: '#6FC9CC'
  violet: '#3F136C'
  violet_50: '#967CB1'
  fuchsia: '#A80163'
  fuchsia_50: '#D067AD'
  light_gray: '#B2B3B5'
  light_gray_50: '#D7D7Da'
  dark_blue: '#08427E'
  dark_blue_50: '#6D9ABC'